# -*- coding: utf-8 -*-
"""Extractive Summary_distilbart.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i6WQpo6pS-N9lEXZJw2Xfpo0wL6JOObc
"""

import numpy as np
import pandas as pd
import os
import io
!pip install transformers 
import transformers

from tqdm import tqdm

from google.colab import drive
drive.mount('/content/drive')

# Change the current working directory to specified path
os.chdir('drive/My Drive/Colab Notebooks/Data-Source/Auto_Text_Summarization/')

dfTrain = pd.read_csv('train.csv', error_bad_lines = False, engine = "python")
dfTest = pd.read_csv('test.csv')

print(dfTrain.shape)
print(dfTrain.head())

print(dfTest.shape)
print(dfTest.head())

#Loading the HuggingFace summarization pipeline
from transformers import pipeline

# Initialize the HuggingFace summarization pipeline
summarizer = pipeline('summarization')


li=[]  # list to store extractive summaries
li_highlights=[] #list to store original summary

for i in range(0,10000):  # running for 10000 records

    text=train_df['article'][i]  # Original Article column of train data
    text=text[0:2048]

    #passing the input to summarizer Pipeline of Hugging Face transformer and generating the summaries
    value=summarizer(text,max_length=300,min_length=30) 
    li.append(value[0]['summary_text']) 

    #storing the original summaries of train data
    text_high=train_df['highlights'][i]
    li_highlights.append(text_high)


#dataframe to store the extracted summaries & original summaries
data={'original_summary':li_highlights,'distilbart-cnn-12-6':li}
df=pd.DataFrame(data)

#saving the dataframe to csv
df.to_csv('out_{}.csv'.format(i))  